### ISSUE TITLE
Modals

### ISSUE THREAD

**Issue by eXo5** [react-materialize/react-materialize.github.io#11]
Can I get an example of how to utilize the modalOptions? I was hoping to use something like modalOptions={ready: function()} but I couldn't for the life of me get it figured out. Can you provide any clarity or insight?

**Comment by alextrastero** [comment]
```js
<Modal
	header='Modal Header'
	modalOptions={{ dismissible: false, ready: () => { console.log('ready'); } }}
	trigger={<Button>MODAL</Button>}>
	<p>Lorem ipsum</p>
</Modal>
```
Hope this helps, it would be great if an example was added to the Docs (if you feel like contributing :))

**Comment by eXo5** [comment]
I created a pull request - but I don't think this is the same type of
examples as you have. I do think it would provide a little more clarity on
how to use modalOptions though.
