### ISSUE TITLE
No source code in the documentation

### ISSUE THREAD

**Issue by katendeglory** [react-materialize/react-materialize.github.io#16]
Hi, I've come across you framework and wanted to read through the doc in order to try it out.

The home page quote "Navigate through these docs to see available components. Click on "Show Info" to view each story source".

I've search every inch of the web site but couldn't find where "Show Info" was mentioned, in order to access the code. is there any alternative methods?

**Comment by alextrastero** [comment]
Yes, I was in panic mode trying to solve the react conflict issue, i've restored it in 3.5.6, really sorry about the inconvenience.

**Comment by katendeglory** [comment]
It is working now. thanks a lot, I'm loving this package and I believe it is seriously underrated. 😀😀
